## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
p = [[1, 0], 
     [0, 1]]
q = [[1, 2], 
     [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


## Write a NumPy program to compute the determinant of a given square array

In [3]:
a = np.array([[1, 0], 
              [1, 2]])
print(np.linalg.det(a))


2.0


## Write a NumPy program to compute the cross product of two given vectors

In [4]:
p = [[1, 0], 
     [0, 1]]
q = [[1, 2], 
     [3, 4]]
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross prod")
print(result2)

cross product of the said two vectors(p, q):
[ 2 -3]
cross prod
[-2  3]


## Write a NumPy program to compute the condition number of a given matrix

In [6]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("The condition number of the said matrix:")
print(np.linalg.cond(a))

The condition number of the said matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [8]:
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print(np.linalg.inv(a))

[[ 0.5  0.   0.5]
 [ 0.   1.   0. ]
 [-0.5  0.   0.5]]
